Lesson 8
Dmitriy-Filatov/thinknetica-RoR pull request #10
Opened 2022-10-01 15:21 UTC by Dmitriy-Filatov

1. Реализуйте все стандартные действия вместе с представлениями (видами) для ресурса вопросов:
Список вопросов теста должен выводиться на той же странице, что и сам тест
Используйте фрагменты представлений там, где это уместно
Для того чтобы метод form_with смог сформировать верный URL используйте вызов form_with model: [@parent, @child]
В представлениях должны быть ссылки для навигации между страницами приложения

2. Добавьте футер в котором будет выводиться текущий год, имя автора, название проекта (в виде ссылки на GitHub-репозиторий проекта), его краткое описание и ссылка с текстом "Учебный проект в онлайн-школе Thinknetica", ведущая на адрес [thinknetica.com](http://thinknetica.com/)

3. Напишите хэлперы:
Для заголовка формы создания и редактирования вопроса. Это должен быть один метод question_header который в форме создания вопроса будет выводить Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
Для вывода текущего года в футере
Для формирования ссылки на GitHub репозиторий: github_url(author, repo)

4. Добавьте в представление списка тестов количество вопросов для каждого теста

2022-10-01 19:11 UTC, BubuntuClu requested changes

2022-10-01 19:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      question = Question.create(question_params)
не переписал
https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/6#discussion_r973745525

2022-10-01 19:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
у тебя есть колбэк на поиск вопроса, зачем тут ищешь еще раз?

2022-10-01 19:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
и тут.

2022-10-01 19:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>      render plain: 'The question has been deleted.'
если ты делаешь редирект, то зачем тут рендер?

2022-10-01 19:11 UTC, BubuntuClu commented on app/views/tests/show.html.erb
> +<h1> Selected test: </h1>
>Список вопросов теста должен выводиться на той же странице, что и сам тест

не увидел этого пункта

2022-10-01 19:11 UTC, BubuntuClu commented on app/controllers/questions_controller.rb
>    def index
`resources :questions, shallow: true, except: :index`
ты убрал роут для экшена `index`, тогда надо и сам экшен убрать, чтобы он не мешал своим кодом в контроллере. и колбэк почистить от этого экшена

2022-10-04 14:20 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
>      question = Question.create(question_params)
Вот https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/6

2022-10-04 14:22 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
>      question = Question.create(question_params)
ebefd76981e306965b013610abb454f71aed184b 
464816a6f5ed8c10bb0306fad3b6dfde86fdd01b
Готово.

2022-10-04 14:23 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
>      render plain: 'The question has been deleted.'
Строка 44 ebefd76981e306965b013610abb454f71aed184b

2022-10-04 14:31 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
84505c511344ae839a85485f3003aff762e7780b

2022-10-04 14:35 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
> +    @question = Question.find(params[:id])
a9b5cf03a0c8f4ca170f167a8d7296ae5f575396

2022-10-04 14:40 UTC, Dmitriy-Filatov commented on app/controllers/questions_controller.rb
>    def index
05b8944886074d112623e83c9cc75349ddd39f3d

2022-10-04 14:46 UTC, Dmitriy-Filatov commented on app/views/tests/show.html.erb
> +<h1> Selected test: </h1>
95485a88b271010184571174413ea32c3fd08243

2022-10-05 09:05 UTC, merged