Lesson 9
Dmitriy-Filatov/thinknetica-RoR pull request #11
Opened 2022-10-15 15:01 UTC by Dmitriy-Filatov

1. Сделайте назначение следующего вопроса в модели TestPassage с помощью обратного вызова
2. Доработайте шаблон результата прохождения теста:
Выводите сообщение и процент успеха в зависимости от количества правильных ответов
Если процент успеха >= 85% число должно быть зелёного цвета и сообщение должно говорить об успешном прохождении теста
Если процент успеха < 85% число должно быть красного цвета и сообщение должно говорить о том что тест не пройден
Добавьте навигацию в виде ссылки на список всех тестов
3. Доработайте шаблон отображения прохождения теста:
Выводите номер текущего вопроса и общее количество вопросов теста

Возможен более простой способ реализации проверки правильного ответа:

correct_answers.ids.sort == answer_ids.map(&:to_i).sort

2022-10-15 17:19 UTC, BubuntuClu requested changes

2022-10-15 17:19 UTC, BubuntuClu commented on app/controllers/answers_controller.rb
> +    @answer = Answer.new(answer_params)
создавай ответ через ассоциацию вопроса. сейчас у тебя ответ никогда не будет создан успешно

2022-10-15 17:19 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +  end
чтобы вернуть нужный текст ты дважды выполняешь одну и туже логику. не оптимально, представь что метод проверки успеха занимает n времени, при твоей реализации отрисовка будет занимать 2n времени

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/answer.rb
> -  validates :body, presence: true
куда пропали эти валидации? надо вернуть

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :category#, optional: true
не нужный код удаляй, чтобы он никого не смущал

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :elementary, -> { where(level: 2) }
в скоупе `easy` ты используешь скоуп `level`, а тут и ниже почему перестал его использовать?

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    @result_message = result_percent >= 85
без контекста 85 это магическое число, вынеси в константу и обзови ее понятно

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +    self.current_question = next_question if test.present?
может не быть теста?

2022-10-15 17:19 UTC, BubuntuClu commented on app/models/test_passage.rb
> +  def next_question
плохой нейминг методов. в чем между ними разница? кроме того что один возвращает массив, а другой один элемент?

2022-10-15 17:19 UTC, BubuntuClu commented on db/migrate/20221011110616_drop_table_tests_users.rb
> +  def up
если есть метод `up`, то должен быть и метод `down`, чтобы при откатывании миграции не словить ошибку.
в данном случае, метод `down` можно оставить пустым

2022-10-17 14:09 UTC, Dmitriy-Filatov commented on app/models/answer.rb
> -  validates :body, presence: true
Вернул. ****

2022-10-17 14:10 UTC, Dmitriy-Filatov commented on app/models/answer.rb
> -  validates :body, presence: true
Вернул. f61203cee50c9c8fb37052efc1c7b96ae9902b8b

2022-10-17 19:40 UTC, BubuntuClu requested changes

2022-10-17 19:40 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <span class="passage-result <%= success_failure(@test_passage) %>" >
success_failure такого метода нет в коде. упадет приложение с ошибкой

2022-10-17 19:40 UTC, BubuntuClu commented on app/views/test_passages/result.html.erb
> +  <span class="passage-result <%= success_failure(@test_passage) %>" >
и этот код видимо должен был отвечать за цвет надписи? надо реализовать этот код

2022-10-18 06:28 UTC, BubuntuClu requested changes

2022-10-18 06:28 UTC, BubuntuClu commented on app/helpers/test_passages_helper.rb
> +    @test_passage.success? ? 'success' : 'failure'
ты вернулся к тому что было изначально. два метода, которые вызывают одну и туже проверку успеха. смысл был в том чтобы от этого отказаться

2022-10-19 08:50 UTC, merged