Lesson 2
Dmitriy-Filatov/thinknetica-RoR pull request #2
Opened 2021-12-06 20:49 UTC by Dmitriy-Filatov

1. Создайте Rails-модели с нужными атрибутами для следующих сущностей:
Тест
Вопрос
Ответ
Пользователь
Категория
2. С помощью механизма миграций, добавьте ограничения целостности на уровне БД в соответствующих таблицах для необходимых атрибутов так, чтобы они не могли содержать значение NULL
3. С помощью механизма миграций добавьте значения по умолчанию:
Для уровня Теста
Для атрибута correct у Ответа

2021-12-06 20:59 UTC, Dmitriy-Filatov commented
1. Создание моделей https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/2/commits/2bf9f0e092c985c43e55261ec3f40390efe1259a
2. Добавление ограничения целостности https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/2/commits/0c157497e83e7914dd964f36457959fc35670ce3
3. Добавление значения по умолчанию https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/2/commits/66eab6da51fcdc3a10912332d3758105e2b3493b

2021-12-07 07:06 UTC, BubuntuClu requested changes

2021-12-07 07:06 UTC, BubuntuClu commented on db/migrate/20211206192117_create_tests.rb
> +      t.belongs_to :categories, foreign_key: true
принадлежит одному объекту. тут должно быть единственное число категорий

2021-12-07 07:06 UTC, BubuntuClu commented on db/migrate/20211206193518_create_questions.rb
> +      t.belongs_to :tests, foreign_key: true
единственное число тестов

2021-12-07 07:06 UTC, BubuntuClu commented on db/migrate/20211206194410_create_answers.rb
> +      t.belongs_to :questions, foreign_key: true
единственное число вопросов

2021-12-07 07:06 UTC, BubuntuClu commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
все ограничения/дефолтные значения и тд стоит задавать сразу при создании таблицы, чтобы не было 100500 миграций на каждый чих

2021-12-07 07:06 UTC, BubuntuClu commented on db/schema.rb
> +    t.integer "questions_id"
в этом файле ты можешь посмотреть что в итоге у тебя создалось в бд. тут видно что этот столбец имеет неправильное название. тут должно быть `question_id`, так как связь идет с одним объектом.
надо поправить замечания в миграциях, тогда тут ошибка исправится

2021-12-07 07:32 UTC, Dmitriy-Filatov commented on db/migrate/20211206192117_create_tests.rb
> +      t.belongs_to :categories, foreign_key: true
А, точно. Таблица же одна. Ссылка на имя таблицы, а не на имя столбца ...

2021-12-07 07:33 UTC, Dmitriy-Filatov commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
Теперь надо удалить тест и создать заново?

2021-12-07 07:34 UTC, Dmitriy-Filatov commented on db/schema.rb
> +    t.integer "questions_id"
Спасибо, учту.

2021-12-07 07:51 UTC, Dmitriy-Filatov commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
в задании это отдельным пунктом после создания моделей ...

2021-12-07 07:51 UTC, Dmitriy-Filatov commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
Как теперь лучше поступить?

2021-12-07 14:18 UTC, BubuntuClu commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
сейчас можно оставить так, но на будущее лучше сразу все прописывать

2021-12-07 14:19 UTC, BubuntuClu commented on db/migrate/20211206200932_add_tests_title_null_constraint.rb
> +class AddTestsTitleNullConstraint < ActiveRecord::Migration[6.1]
>Теперь надо удалить тест и создать заново?

что за тест?

 можно просто откатить все миграции, удалить лишние, оставить 5 миграций на создание таблиц со всеми ограничениями

2021-12-13 18:51 UTC, merged