Lesson 5
Dmitriy-Filatov/thinknetica-RoR pull request #4
Opened 2022-03-21 20:15 UTC by Dmitriy-Filatov

https://github.com/Dmitriy-Filatov/thinknetica-RoR/wiki/ER-Diagramm

2022-03-22 06:31 UTC, BubuntuClu requested changes

2022-03-22 06:31 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
как работает эта связь? за счет какой таблицы и колонки в бд?

2022-03-22 19:13 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
сейчас никак не работает. Удалил эту связь пока что. https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/33493e1d7160c59606bcabc0cd080a65be366516

2022-03-23 08:03 UTC, BubuntuClu commented on app/models/test.rb
> +  belongs_to :author, class_name: 'User'
надо ее реализовать по условиям задания `Между Тестом и автором (Пользователем), который его создал.`. должна быть связь у тестов с автором. и у автора с созданными тестами

2022-03-24 06:41 UTC, BubuntuClu requested changes

2022-03-24 06:41 UTC, BubuntuClu commented on db/migrate/20211206192117_create_tests.rb
> +      t.belongs_to :author, class_name: 'User'
нельзя править миграции, которые уже смержены. удалить отсюда этот код

2022-03-24 06:41 UTC, BubuntuClu commented on db/migrate/20220323202140_add_column_to_tests.rb
> +    add_column :tests, :author_id, :integer
это должен быть еще и внешний ключ, а не просто колонка

2022-03-26 23:59 UTC, Dmitriy-Filatov commented on db/migrate/20220323202140_add_column_to_tests.rb
> +    add_column :tests, :author_id, :integer
не смог написать миграцию по дабавлению внешнего ключа.
прописал вручную в схеме
https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/4/files/e0246fd7e05d00bd8eb9ca1f24778d5c1acbaad3..23b959ad9e336b4f9b3327b3326654c05fd3155f#diff-cbf8b25d6d853acf58fa9057841f407d29ffe90649c75cf9e3f51b2d6e3aa1d3R42

2022-03-27 00:02 UTC, Dmitriy-Filatov commented on db/migrate/20211206192117_create_tests.rb
> +      t.belongs_to :author, class_name: 'User'
удалил

2022-03-27 16:54 UTC, BubuntuClu requested changes

2022-03-27 16:54 UTC, BubuntuClu commented on db/migrate/20220323202140_add_column_to_tests.rb
> +    add_column :tests, :author_id, :integer
от того что ты ее в схеме прописал, это не значит что этот ключ появился в БД. схема это результат выполнения твоих миграций, это не реальная структура твоей БД, которую ты можешь править руками. 

в чем сложность возникла с добавлением внешнего ключа?

2022-03-28 06:45 UTC, BubuntuClu requested changes

2022-03-28 06:45 UTC, BubuntuClu commented on db/migrate/20220323202140_add_column_to_tests.rb
> +    add_column :tests, :author_id, :integer
теперь `add_column` надо удалить. сейчас поулчается ты создаешь две одинаковые колонки. ты тут получить ошибку должен при накате такой миграции. после того как оставишь добавление внешнего ключа, тебе еще две ассоциации надо добавить, на автора у тестов и на созданные тесты у пользователя

2022-03-29 17:31 UTC, Dmitriy-Filatov commented
@BubuntuClu , закрываю?

2022-03-29 17:48 UTC, Dmitriy-Filatov commented
@BubuntuClu , спасибо!

2022-03-29 17:51 UTC, merged