Lesson 6 Validations and scopes
Dmitriy-Filatov/thinknetica-RoR pull request #5
Opened 2022-03-31 20:47 UTC by Dmitriy-Filatov

2022-04-01 07:56 UTC, BubuntuClu requested changes

2022-04-01 07:56 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc).pluck(:title) }
сортировку и выборку не надо помещать в скоуп.
скоуп должен возвращать объект ActiveRecord::Relation, pluck возвращает массив.
так же скоуп это универсальный метод, который может использован в разных частях приложения, там может потребоваться другая сортировка и выборка.
метод надо оставить, заменить часть выражения на скоуп и уже к скоупу применить сортировку и выборку

2022-04-01 07:56 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
`validates :title, presence: true, uniqueness: { scope: :level, case_sensitive: false, message: 'already exists' }`

2022-04-01 07:56 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
ограничения надо дублировать на всех уровнях приложения. можно через СУБД насоздавать данных, которые для приложения не будут валидны. в БД добавить уникальный составной индекс надо

2022-04-01 07:56 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1) }
ты можешь использовать свой скоуп `level` внутри этого скоупа, чтобы не писать условие

2022-04-06 21:57 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc).pluck(:title) }
@BubuntuClu https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/0cdd27ed839d0c6a8c8bbecde6d9fd20914d8337

2022-04-06 21:59 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  validates :title, presence: true
@BubuntuClu https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/0cdd27ed839d0c6a8c8bbecde6d9fd20914d8337

все равно запутался ...

2022-04-06 22:00 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  validates :title, presence: true
@BubuntuClu https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/0cdd27ed839d0c6a8c8bbecde6d9fd20914d8337

Добавил

2022-04-06 22:04 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc).pluck(:title) }
Вот https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/a56a5b90fbacc34e64a4022f9d4ceeccd9a520f2

2022-04-06 22:05 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc).pluck(:title) }
@BubuntuClu вот https://github.com/Dmitriy-Filatov/thinknetica-RoR/commit/a56a5b90fbacc34e64a4022f9d4ceeccd9a520f2

2022-04-06 22:14 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1) }
@BubuntuClu а тут не понял

2022-04-07 06:36 UTC, BubuntuClu approved these changes

2022-04-07 06:36 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1) }
`scope :easy, -> { level(0..1) } `

2022-04-07 06:36 UTC, BubuntuClu commented on app/models/test.rb
> +  validates :title, presence: true
строку 8 и 10 можно объединить, как я написал выше в комменте

2022-04-07 06:36 UTC, BubuntuClu commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc) }
сортировку не вынес из скоупа

2022-04-07 06:36 UTC, BubuntuClu commented on app/models/test.rb
> +  def self.returns_array_of_titles_of_all_tests_by_category_title(title)
можно сократить до `titles_tests_by_category`
и так понятно что вернется что-то поэтому `returns` лишнее. `array` тоже раз во множественном числе запрашиваем что-то

2022-04-07 09:41 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  def self.returns_array_of_titles_of_all_tests_by_category_title(title)
@BubuntuClu а, ну тут я дословно перевел, как в задании)

2022-04-07 18:52 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  def self.returns_array_of_titles_of_all_tests_by_category_title(title)
[dfe0168](https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/5/commits/dfe016893596ae67c9c3cab248c5c7df9f889dd9)

2022-04-07 18:53 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  def self.returns_array_of_titles_of_all_tests_by_category_title(title)
@BubuntuClu поменял [dfe0168](https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/5/commits/dfe016893596ae67c9c3cab248c5c7df9f889dd9)

2022-04-07 19:28 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc) }
@BubuntuClu правильно? [7093fdd](https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/5/commits/7093fdd824199a6d506b2efc9cb54ea627a6a074)

2022-04-07 19:35 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :get_categories_by_title, ->(title) { joins(:category).where(category: { title: title }).order(title: :desc).pluck(:title) }
@BubuntuClu правильно? https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/5/commits/7093fdd824199a6d506b2efc9cb54ea627a6a074

2022-04-07 19:39 UTC, Dmitriy-Filatov commented on app/models/test.rb
> +  scope :easy, -> { where(level: 0..1) }
@BubuntuClu  так верно? https://github.com/Dmitriy-Filatov/thinknetica-RoR/pull/5/commits/3483f24a0d5485899703cebcdeff8ee9f38990c8

2022-04-08 06:37 UTC, BubuntuClu approved these changes

2022-04-08 07:43 UTC, merged